import type { BloodBank, DonationRequest, Donor } from "./types"

export const mockBloodBanks: BloodBank[] = [
  {
    id: "1",
    name: "City General Blood Bank",
    address: "123 Medical Center Dr",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    phone: "(415) 555-0100",
    email: "contact@citygeneralbb.org",
    latitude: 37.7749,
    longitude: -122.4194,
    operatingHours: "Mon-Fri: 8AM-6PM, Sat: 9AM-3PM",
    inventory: [
      { bloodType: "A+", unitsAvailable: 45, lastUpdated: new Date() },
      { bloodType: "A-", unitsAvailable: 12, lastUpdated: new Date() },
      { bloodType: "B+", unitsAvailable: 28, lastUpdated: new Date() },
      { bloodType: "B-", unitsAvailable: 8, lastUpdated: new Date() },
      { bloodType: "AB+", unitsAvailable: 15, lastUpdated: new Date() },
      { bloodType: "AB-", unitsAvailable: 5, lastUpdated: new Date() },
      { bloodType: "O+", unitsAvailable: 67, lastUpdated: new Date() },
      { bloodType: "O-", unitsAvailable: 18, lastUpdated: new Date() },
    ],
  },
  {
    id: "2",
    name: "Memorial Hospital Blood Center",
    address: "456 Healthcare Blvd",
    city: "Oakland",
    state: "CA",
    zipCode: "94612",
    phone: "(510) 555-0200",
    email: "info@memorialblood.org",
    latitude: 37.8044,
    longitude: -122.2712,
    operatingHours: "Mon-Sun: 7AM-7PM",
    inventory: [
      { bloodType: "A+", unitsAvailable: 38, lastUpdated: new Date() },
      { bloodType: "A-", unitsAvailable: 10, lastUpdated: new Date() },
      { bloodType: "B+", unitsAvailable: 22, lastUpdated: new Date() },
      { bloodType: "B-", unitsAvailable: 6, lastUpdated: new Date() },
      { bloodType: "AB+", unitsAvailable: 12, lastUpdated: new Date() },
      { bloodType: "AB-", unitsAvailable: 4, lastUpdated: new Date() },
      { bloodType: "O+", unitsAvailable: 54, lastUpdated: new Date() },
      { bloodType: "O-", unitsAvailable: 14, lastUpdated: new Date() },
    ],
  },
]

export const mockDonationRequests: DonationRequest[] = [
  {
    id: "1",
    recipientId: "r1",
    recipientName: "Sarah Johnson",
    bloodType: "O-",
    unitsNeeded: 2,
    urgencyLevel: "critical",
    hospital: "City General Hospital",
    city: "San Francisco",
    state: "CA",
    requestDate: new Date(Date.now() - 2 * 60 * 60 * 1000),
    status: "open",
  },
  {
    id: "2",
    recipientId: "r2",
    recipientName: "Michael Chen",
    bloodType: "A+",
    unitsNeeded: 3,
    urgencyLevel: "urgent",
    hospital: "Memorial Hospital",
    city: "Oakland",
    state: "CA",
    requestDate: new Date(Date.now() - 5 * 60 * 60 * 1000),
    status: "open",
  },
  {
    id: "3",
    recipientId: "r3",
    recipientName: "Emily Rodriguez",
    bloodType: "B+",
    unitsNeeded: 1,
    urgencyLevel: "moderate",
    hospital: "St. Mary Medical Center",
    city: "San Jose",
    state: "CA",
    requestDate: new Date(Date.now() - 24 * 60 * 60 * 1000),
    status: "open",
  },
]

export const mockCurrentDonor: Donor = {
  id: "d1",
  email: "john.doe@example.com",
  name: "John Doe",
  phone: "(555) 123-4567",
  role: "donor",
  bloodType: "O+",
  dateOfBirth: new Date("1990-05-15"),
  address: "789 Donor Street",
  city: "San Francisco",
  state: "CA",
  zipCode: "94103",
  lastDonationDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
  isEligible: true,
  totalDonations: 12,
  createdAt: new Date("2022-01-15"),
}
